---
- name: Install rsyslog package
  become: true
  apt:
    name:
      - rsyslog
  when:
    - use_rsyslog
  tags:
    - apt
    - packages

- name: Set fact to unify variables
  set_fact:
    rsyslog_use_remote: true
  when:
    - "'rsyslog_elks' in group_names"
    - not rsyslog_use_remote

- name: Get rsyslog package status and version
  command: >
    dpkg-query --show \
      --showformat '{"version":"${Version}","status":"${db:Status-Abbrev}"}' \
      rsyslog
  when:
    - rsyslog_use_remote
  changed_when: false
  check_mode: no
  register:
    rsyslog_status

- name: Set fact from rsyslog version
  set_fact:
    rsyslog_ver_major: "{{ (rsyslog_status.stdout|from_json).version.split('.')[0] }}"
    rsyslog_ver_minor: "{{ (rsyslog_status.stdout|from_json).version.split('.')[1] }}"
  check_mode: no
  when:
    - rsyslog_status.stdout is defined
    - (rsyslog_status.stdout|from_json).status|trim == "ii"

- name: Central log server does not need 'last message repeated'
  become: true
  lineinfile:
    path: /etc/rsyslog.conf
    line: '$RepeatedMsgReduction off'
    regexp: '^\$RepeatedMsgReduction '
    insertafter: "^# Filter duplicated messages"
    validate: rsyslogd -N2 -f %s
  notify: restart rsyslog
  when:
    - rsyslog_use_remote

- name: When logging to central log server use full name
  become: true
  lineinfile:
    path: /etc/rsyslog.conf
    line: '$PreserveFQDN on'
    regexp: '^\$PreserveFQDN '
    insertbefore: '^\$IncludeConfig '
    validate: rsyslogd -N2 -f %s
  notify: restart rsyslog
  when:
    - rsyslog_use_remote

- name: Syslog to log to central log server
  become: true
  become_user: root
  template:
    src: rsyslog-elks.conf.j2
    dest: "/etc/rsyslog.d/{{ rsyslog_forwarder_filename }}"
    mode: 0644
    owner: 0
    group: 0
    validate: rsyslogd -N2 -f %s
  notify: restart rsyslog
  when:
    - rsyslog_use_remote

...
